spring:
  data:
    mongodb:
      database: BlogReactive
      host: 10.131.155.57
      port: 27017
      username: root
      password: admin
      authentication-database: admin
      
server:
  port: 8086
